# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('goodsandservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('goodandservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goodsandservices.goodandservice')),
                ('minimumStock', models.FloatField(default=0, null=True)),
                ('quantityInStock', models.FloatField(default=0, null=True)),
                ('cal', models.FloatField(default=0, null=True)),
                ('car', models.FloatField(default=0, null=True)),
                ('pro', models.FloatField(default=0, null=True)),
                ('fat', models.FloatField(default=0, null=True)),
                ('sta', models.FloatField(default=0, null=True)),
                ('uomRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.uom')),
            ],
            bases=('goodsandservices.goodandservice',),
        ),
    ]
