# Generated by Django 3.1.3 on 2020-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantityInStock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
