# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateTimeField(null=True)),
                ('startAt', models.DateTimeField(null=True)),
                ('expectedEndAt', models.DateTimeField(null=True)),
                ('cost', models.FloatField(default=0)),
                ('revenue', models.FloatField(default=0)),
            ],
        ),
    ]
