# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('menues', '0001_initial'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='associatedMenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menues.menu'),
        ),
        migrations.AddField(
            model_name='event',
            name='personnelles',
            field=models.ManyToManyField(to='personnels.Personnel'),
        ),
    ]
