# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparationDate', models.DateTimeField(auto_now_add=True)),
                ('startTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('serving', models.IntegerField()),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving', models.IntegerField()),
                ('preparation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparations.preparation')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredient')),
                ('preparationLine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preparations.preparationline')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.uom')),
            ],
        ),
    ]
