# Generated by Django 3.1.3 on 2020-11-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcenters', '0001_initial'),
        ('goodsandservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservice',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costcenters.costcenter'),
        ),
    ]
