# Generated by Django 3.1.3 on 2020-11-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsandservices', '0002_auto_20201112_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservice',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
