# Generated by Django 3.1.3 on 2020-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsandservices', '0003_auto_20201112_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodandservice',
            name='costControllability',
            field=models.CharField(choices=[('f', 'Fixed'), ('v', 'Variable')], default='c', max_length=12),
        ),
        migrations.AddField(
            model_name='goodandservice',
            name='costVariability',
            field=models.CharField(choices=[('f', 'Fixed'), ('v', 'Variable')], default='v', max_length=12),
        ),
    ]
