# Generated by Django 3.1.3 on 2021-02-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsandservices', '0004_auto_20201222_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservice',
            name='costControllability',
            field=models.CharField(choices=[('f', 'Fixed'), ('v', 'Variable')], default='c', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='goodandservice',
            name='costVariability',
            field=models.CharField(choices=[('f', 'Fixed'), ('v', 'Variable')], default='v', max_length=12, null=True),
        ),
    ]
