# Generated by Django 3.1.3 on 2020-11-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsandservices', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('note', models.TextField()),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodsandservices.goodandservice')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generalorders.order')),
                ('uon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.uom')),
            ],
        ),
    ]
