# Generated by Django 3.1.3 on 2020-11-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pe', 'Pending'), ('su', 'Submitted'), ('ca', 'Cancelled')], default='pe', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
