# Generated by Django 3.1.3 on 2020-11-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalorders', '0003_auto_20201112_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='OrderDate',
        ),
    ]
