# Generated by Django 3.1.3 on 2020-11-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalorders', '0004_auto_20201112_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrderDate',
            new_name='orderDate',
        ),
    ]
