# Generated by Django 3.1.3 on 2020-11-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalorders', '0005_auto_20201112_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
