# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restauranttables', '0001_initial'),
        ('menues', '0001_initial'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('request', models.TextField()),
                ('cronology', models.CharField(choices=[('n', 'Now'), ('f', 'Follows'), ('f2', 'second Follows')], max_length=30, null=True)),
                ('menuItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menues.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Comande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCollectedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('waitingMinutes', models.IntegerField()),
                ('restaurantTable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restauranttables.table')),
                ('weiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnels.personnel')),
            ],
        ),
    ]
