# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('quantityInUomIngredient', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
