# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(null=True)),
                ('name', models.CharField(default='Costumer', max_length=40, null=True)),
                ('pax', models.IntegerField()),
                ('telephone', models.CharField(max_length=40, null=True)),
                ('specialRequest', models.TextField()),
            ],
        ),
    ]
