# Generated by Django 3.1.3 on 2020-11-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fd', 'Food'), ('nf', 'Non Food'), ('se', 'Service')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
