# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=60)),
                ('nickName', models.CharField(max_length=20)),
                ('hourlyWage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDate', models.DateTimeField()),
                ('startWorking', models.DateTimeField()),
                ('endWorking', models.DateTimeField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnels.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnels.role'),
        ),
    ]
