# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('platingimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('servings', models.IntegerField()),
                ('preptime', models.IntegerField(blank=True, null=True)),
                ('cooktime', models.IntegerField(blank=True, null=True)),
                ('directions', models.TextField()),
                ('calories', models.FloatField(blank=True, null=True)),
                ('car', models.FloatField(blank=True, null=True)),
                ('pro', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('sta', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('durationMin', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredient')),
                ('recipeLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipeline')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.uom')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measurements.uom')),
            ],
        ),
    ]
