# Generated by Django 3.1.3 on 2020-11-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsandservices', '0003_auto_20201112_0010'),
        ('recipes', '0004_auto_20201130_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='goodandservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goodsandservices.goodandservice'),
        ),
    ]
