# Generated by Django 3.1.3 on 2020-11-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20201112_0817'),
        ('recipes', '0005_auto_20201130_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='goodandservice',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredient'),
        ),
    ]
