# Generated by Django 3.1.3 on 2020-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201130_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
