# Generated by Django 3.1.3 on 2020-12-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='my recipe', max_length=100),
        ),
    ]
