# Generated by Django 3.1.3 on 2020-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20201204_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='importance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
