# Generated by Django 3.1.3 on 2020-12-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20201215_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooktime_1_temp',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooktime_2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooktime_2_temp',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooktime_3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooktime_3_temp',
        ),
    ]
