# Generated by Django 3.1.3 on 2020-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_recipe_cooktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingprogramphase',
            name='phaseNumber',
            field=models.IntegerField(default=1),
        ),
    ]
