# Generated by Django 3.1.3 on 2020-11-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceDate', models.DateTimeField(null=True)),
                ('registrationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoiceNumber', models.CharField(max_length=30, null=True)),
                ('total', models.FloatField(default=0)),
                ('totVat', models.FloatField(default=0)),
                ('totalWithWat', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
