# Generated by Django 3.1.3 on 2020-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incominginvoices', '0002_auto_20201110_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='costControllability',
            field=models.CharField(choices=[('f', 'Fixed'), ('v', 'Variable')], default='c', max_length=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='costVariability',
            field=models.CharField(choices=[('f', 'Fixed'), ('v', 'Variable')], default='v', max_length=12),
        ),
    ]
