# Generated by Django 3.1.3 on 2020-12-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incominginvoices', '0003_auto_20201221_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='costControllability',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='costVariability',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contabilized',
            field=models.BooleanField(default=False),
        ),
    ]
