# Generated by Django 3.1.3 on 2020-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0001_initial'),
        ('products', '0002_product_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='allergens.Allergen'),
        ),
    ]
